import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);
  final Locale locale;
  static const supportedLocales = [
    Locale('en'),
    Locale('ar'),
  ];
  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'lang.english': 'English',
      'lang.arabic': 'Arabic',
      'action.continue': 'Continue',
      'action.skip': 'Skip',
      'action.get_started': 'Get Started',
      'action.next': 'Next',
      'action.previous': 'Previous',
      'action.login': 'Login',
      'action.signup': 'Sign Up',
      'action.refresh': 'Refresh',
      'action.change_language': 'Change language',
      'action.cancel': 'Cancel',
      'action.delete': 'Delete',
      'action.ok': 'OK',
      'action.retry': 'Retry',
      'greeting.morning': 'Good morning',
      'greeting.afternoon': 'Good afternoon',
      'greeting.evening': 'Good evening',
      'label.parent_portal': 'Parent Portal',
      'label.safeplay_portal': 'SafePlay Portal',
      'label.welcome_parent': 'Welcome to SafePlay',
      'label.parent_subtitle': 'Your Child\'s Safety is Our Priority',
      'label.language_prompt': 'Choose your language',
      'label.language_description':
          'You can switch anytime from the menu in the parent dashboard.',
      'label.parent_login': 'Parent Login',
      'label.parent_signup': 'Parent Sign Up',
      'label.email': 'Email',
      'label.password': 'Password',
      'label.forgot_password': 'Forgot password?',
      'label.no_account': 'Don\'t have an account?',
      'label.have_account': 'Already have an account?',
      'label.home': 'Parent Dashboard',
      'label.controls': 'Browser Controls',
      'label.wellbeing': 'Wellbeing Reports',
      'label.messaging': 'Messaging Safety',
      'label.nav_home': 'Home',
      'label.nav_controls': 'Controls',
      'label.nav_wellbeing': 'Wellbeing',
      'label.nav_alerts': 'Alerts',
      'label.ai_wellbeing': 'AI wellbeing report',
      'label.recent_checkins': 'Recent check-ins',
      'label.this_weeks_mood': 'This week\'s mood',
      'label.browser_activity': 'Browser Activity History',
      'label.privacy_note':
          'Summaries stay abstract (no raw notes) and are meant to support gentle conversations.',
      'browser.summary_hint':
          'High-level summary of recent online activity. Privacy-focused insights.',
      'browser.error_title': 'Unable to load recent browsing insights.',
      'browser.empty': 'Not enough Safe Browser activity for a summary yet.',
      'label.language_setting': 'Language',
      'label.language_setting_desc':
          'Switch between English and Arabic for the parent experience.',
      'settings.title': 'Settings',
      'settings.subtitle': 'Manage your account and preferences',
      'settings.change_password': 'Change Password',
      'settings.change_password_desc': 'Update your account password',
      'settings.notifications': 'Notifications',
      'settings.notifications_desc': 'Manage notification preferences',
      'settings.privacy': 'Privacy & Security',
      'settings.privacy_desc': 'Manage your privacy settings',
      'settings.help': 'Help & Support',
      'settings.help_desc': 'Get help and contact support',
      'settings.logout': 'Log Out',
      'settings.delete_account': 'Delete Account',
      'settings.delete_account_desc':
          'Permanently delete your account and all data',
      'settings.sign_out': 'Sign Out',
      'dashboard.active_child': 'Active Child',
      'dashboard.selected': 'Selected',
      'dashboard.children': 'Children',
      'dashboard.streak': 'Streak',
      'dashboard.safety': 'Safety',
      'dashboard.recent_activities': 'Recent Activities',
      'dashboard.screen_time': 'Screen Time Limit',
      'dashboard.screen_time_desc': 'Daily limit for ',
      'dashboard.enable_screen_time': 'Enable Screen Time Limit',
      'dashboard.daily_limit_label': 'Daily Limit',
      'dashboard.auto_pause':
          'Automatically pause the app when daily limit is reached',
      'dashboard.select_child_limits': 'Select a child to set limits',
      'dashboard.add_child': 'Add Child',
      'dashboard.your_children': 'Your Children',
      'dashboard.no_children': 'No children added yet',
      'dashboard.add_first_child': 'Add your first child to begin',
      'dashboard.remaining_time': 'remaining out of',
      'dashboard.select_child_prompt': 'Select a child',
      'dashboard.managing_children': 'Managing {count} children',
      'dashboard.view_all': 'View all',
      'dashboard.view_less': 'View less',
      'dashboard.add_child_to_see_activities':
          'Add a child to see their recent activities.',
      'dashboard.no_recent_activities': 'No activities yet for {name}.',
      'dashboard.cached_insights':
          'Showing cached insights. Refresh to try again.',
      'dashboard.quick_presets': 'Quick presets',
      'dashboard.minutes': 'minutes',
      'dashboard.hours': 'hours',
      'dashboard.limit_reached':
          'When the time limit is reached, the app will pause automatically.',
      'dashboard.remaining_time_text': '{time} remaining out of {total}',
      'dashboard.age_label': 'Age',
      'dashboard.ready': 'Ready',
      'dashboard.unlock_today': 'Unlock for today',
      'browser.controls_title': 'Browser Controls',
      'browser.safe_search': 'Safe Search',
      'browser.note_privacy':
          'This summary respects privacy by showing abstracted activity patterns, not personal details.',
      'wellbeing.overview': 'Overall wellbeing',
      'wellbeing.recent_checkins': 'Recent check-ins',
      'wellbeing.note_privacy':
          "Meta-level summaries keep kids' privacy intact while still showing trends parents can act on.",
      'wellbeing.add_child_title': 'Add a child first',
      'wellbeing.add_child_subtitle':
          'You need to add a child before viewing wellbeing reports.',
      'wellbeing.select_child_title': 'Select a child',
      'wellbeing.select_child_subtitle':
          'Choose a child from the dropdown above to view their wellbeing data.',
      'wellbeing.no_checkins_title': 'No check-ins yet',
      'wellbeing.no_checkins_message':
          "Encourage {name} to share how they're feeling from their dashboard.",
      'wellbeing.child_header': "{name}'s wellbeing",
      'wellbeing.last_shared': 'Last shared {timestamp}',
      'wellbeing.latest_note': 'Latest note: {note}',
      'wellbeing.score_label': 'Score',
      'wellbeing.no_mood_week': 'No mood entries yet this week.',
      'wellbeing.no_recent_checkins': 'No wellbeing check-ins recorded yet.',
      'wellbeing.no_note_added': 'No note added',
      'wellbeing.checkin_yesterday': 'Yesterday • {time}',
      'wellbeing.checkin_day_time': '{day} • {time}',
      'wellbeing.mood.amazing': 'Amazing',
      'wellbeing.mood.happy': 'Happy',
      'wellbeing.mood.good': 'Good',
      'wellbeing.mood.okay': 'Okay',
      'wellbeing.mood.sad': 'Sad',
      'wellbeing.mood.upset': 'Upset',
      'wellbeing.tag.mood_trends': 'Mood trends',
      'wellbeing.tag.recent_week': 'This week',
      'messaging.title': 'Messaging Safety',
      'messaging.alerts': 'AI Alerts',
      'messaging.alert_inappropriate': 'Inappropriate Language',
      'messaging.alert_detected': 'Detected recently',
      'activity.teacher_assigned': 'Teacher-assigned session',
      'activity.single_min_session': '1 min session',
      'activity.minutes_session': '{minutes} min session',
      'activity.learning': 'Learning',
      'child.age_value': 'Age {age}',
      'child.age_not_set': 'Age not set',
      'child.grade_value': 'Grade {grade}',
      'child.streak_value': '{days} day streak',
      'child.login_ready': 'Login Ready',
      'child.setup_login': 'Setup Login',
      'child.age_group_junior': 'Junior',
      'child.age_group_bright': 'Bright',
      'child.list_header': 'Your Children ({count})',
      'child.empty_title': 'No children added yet',
      'child.empty_subtitle':
          'Add your first child to start tracking their learning journey',
      'child.empty_button': 'Add Your First Child',
      'child.add.title': 'Add Child',
      'child.add.header': 'Create Child Profile',
      'child.add.subtitle':
          'Add your child to start tracking their learning journey',
      'child.add.submit': 'Create Child Profile',
      'child.add.success': 'Child profile created successfully!',
      'child.form.name_label': 'Child\'s Name',
      'child.form.name_error': 'Please enter your child\'s name',
      'child.form.age_label': 'Age',
      'child.form.age_helper': 'Enter an age between 6 and 12',
      'child.form.age_error': 'Please enter your child\'s age',
      'child.form.age_range_error': 'Age must be a number between 6 and 12',
      'child.form.gender_label': 'Gender',
      'child.form.gender_male': 'Male',
      'child.form.gender_female': 'Female',
      'child.form.gender_missing': 'Please select your child\'s gender',
      'child.form.age_group_label': 'Age Group',
      'child.form.age_group_junior': 'Junior Explorer',
      'child.form.age_group_bright': 'Bright Minds',
      'child.form.age_group_junior_desc': 'Ages 6-8',
      'child.form.age_group_bright_desc': 'Ages 9-12',
      'child.form.age_mismatch_title': 'Age Mismatch',
      'child.form.age_mismatch_body':
          'Your child is {age} years old, but {group} is designed for ages {range}.',
      'child.form.age_mismatch_hint':
          'Please select the appropriate age group or adjust the age.',
      'child.edit.title': 'Edit Child Profile',
      'child.edit.header': 'Edit {name}\'s Profile',
      'child.edit.subtitle':
          'Update your child\'s information and authentication',
      'child.edit.submit': 'Update Child Profile',
      'child.edit.success': 'Child profile updated successfully!',
      'child.auth.section_title': 'Authentication',
      'child.auth.junior': 'Junior Authentication (4 emojis)',
      'child.auth.bright': 'Bright Authentication (3 pictures + PIN)',
      'child.auth.none': 'No authentication set up',
      'child.auth.change': 'Change Authentication',
      'child.auth.setup': 'Set Up Authentication',
      'child.delete.title': 'Delete Child Profile',
      'child.delete.confirm':
          'Are you sure you want to delete {name}\'s profile? This action cannot be undone.',
      'auth.setup.title': 'Setup {name}\'s Login',
      'auth.setup.instructions_emoji':
          'Help your child create a picture password they can remember easily.',
      'auth.setup.instructions_bright':
          'Help your child create a secure login with pictures and a PIN.',
      'auth.setup.how_it_works': 'How it works:',
      'auth.setup.emoji.step1': 'Choose 4 emoji pictures your child likes',
      'auth.setup.emoji.step2': 'Remember the order you select them',
      'auth.setup.emoji.step3': 'Your child will use this sequence to login',
      'auth.setup.emoji.step4': 'Make sure it\'s something they can remember!',
      'auth.setup.pictures.step1': 'Choose 3 pictures your child likes',
      'auth.setup.pictures.step2': 'Create a 4-digit PIN number',
      'auth.setup.pictures.step3': 'Your child will use both to login',
      'auth.setup.pictures.step4': 'Make sure they can remember both!',
      'auth.setup.choose_emojis_title': 'Choose 4 Emojis',
      'auth.setup.choose_emojis_subtitle':
          'Select 4 emoji pictures that {name} will use to login.',
      'auth.setup.choose_pictures_title': 'Choose 3 Pictures',
      'auth.setup.choose_pictures_subtitle':
          'Select 3 pictures that {name} will use to login.',
      'auth.setup.selected_count': 'Selected ({current}/{total}):',
      'auth.setup.confirm_title': 'Confirm {name}\'s Login',
      'auth.setup.confirm_sequence_subtitle':
          'This is the sequence {name} will use to login:',
      'auth.setup.confirm_login_subtitle':
          'This is what {name} will use to login:',
      'auth.setup.login_sequence': 'Login Sequence',
      'auth.setup.remember_sequence':
          'Make sure {name} can remember this sequence!',
      'auth.setup.remember_pin': 'Make sure {name} can remember this PIN!',
      'auth.setup.back': 'Back',
      'auth.setup.start_selection': 'Start Selection',
      'auth.setup.confirm_selection': 'Confirm Selection',
      'auth.setup.save_login': 'Save Login',
      'auth.setup.next': 'Next',
      'auth.setup.select_pictures': 'Select Pictures',
      'auth.setup.create_pin': 'Create PIN',
      'auth.setup.review_setup': 'Review Setup',
      'auth.setup.saving': 'Saving...',
      'auth.setup.pin_title': 'Create PIN',
      'auth.setup.pin_subtitle':
          'Create a 4-digit PIN that {name} can remember.',
      'auth.setup.pin_label': '4-Digit PIN',
      'auth.setup.pin_helper': 'Enter a 4-digit number (e.g., 1234)',
      'auth.setup.pin_error_length': 'PIN must be exactly 4 digits',
      'auth.setup.pin_error_numeric': 'PIN must contain only numbers',
      'auth.setup.pin_confirm_label': 'Confirm PIN',
      'auth.setup.pin_error_mismatch': 'PINs do not match',
      'auth.setup.pin_validation_prompt': 'Enter a 4-digit PIN and confirm it',
      'auth.setup.pin_validation_short': 'PIN must be 4 digits',
      'auth.setup.pin_validation_numeric': 'PIN must contain only numbers',
      'auth.setup.pin_validation_confirm_prompt': 'Please confirm your PIN',
      'auth.setup.pin_validation_confirm_short': 'Confirm PIN must be 4 digits',
      'auth.setup.pin_validation_mismatch': 'PINs do not match',
      'auth.setup.pin_validation_valid': 'PIN is valid!',
      'auth.setup.confirm_selected_pictures': 'Selected Pictures:',
      'auth.setup.confirm_pin_label': 'PIN:',
      'auth.setup.success': 'Login setup completed successfully!',
      'auth.setup.error_prefix': 'Error: ',
      'game.letter_sound_adventure': 'Letter Sound Adventure',
      'game.math_maze': 'Math Maze',
      'game.science_quiz': 'Science Quiz',
      'game.reading_quest': 'Reading Quest',
      'game.shapes_sorter': 'Shapes Sorter',
      'game.number_grid_race': 'Number Grid Race',
      'game.koala_counter_adventure': 'Koala Counter\'s Adventure',
      'game.ordinal_order_challenge': 'Ordinal Order Challenge',
      'game.pattern_builder': 'Pattern Builder',
      'game.bubblepop_grammar': 'BubblePop Grammar',
      'game.seashell_quiz': 'Seashell Quiz',
      'game.fish_tank_quiz': 'Fish Tank Quiz',
      'game.add_equations': 'Add Equations',
      'game.fraction_navigator': 'Fraction Navigator',
      'game.inverse_operation_chain': 'Inverse Operation Chain',
      'game.data_visualization_lab': 'Data Visualization Lab',
      'game.cartesian_grid_explorer': 'Cartesian Grid Explorer',
      'game.memory_match': 'Memory Match',
      'game.word_builder': 'Word Builder',
      'game.story_sequencer': 'Story Sequencer',
      'game.math_adventures': 'Math Adventures',
      'game.reading_adventures': 'Reading Adventures',
      'game.science_adventures': 'Science Adventures',
      'game.number_hunt': 'Number Hunt',
      'game.koala_jumps': 'Koala Jumps',
      'game.pattern_wizard': 'Pattern Wizard',
      'game.equality_explorer_basics': 'Equality Explorer: Basics',
      'game.area_model_introduction': 'Area Model Introduction',
      'game.mean_share_balance': 'Mean: Share and Balance',
      'game.balancing_act': 'Balancing Act',
      'game.states_of_matter_simulation': 'States of Matter Simulation',
      'game.balloons_static_electricity': 'Balloons & Static Electricity',
      'game.exploring_density': 'Exploring Density',
      'game.food_chains': 'Food Chains',
      'game.microorganisms': 'Microorganisms',
      'game.human_body_health_growth': 'Human Body Health & Growth',
      'game.teeth_eating': 'Teeth & Eating',
      'game.plants_animals': 'Plants & Animals',
      'game.keeping_healthy': 'Keeping Healthy',
      'game.how_plants_grow': 'How Plants Grow',
      'game.skeleton_bones': 'Skeleton & Bones',
      'game.plant_animal_differences': 'Plant & Animal Differences',
      'game.life_cycle_plant': 'Life Cycle of a Plant',
      'game.electricity_circuits': 'Electricity Circuits',
      'game.forces_in_action': 'Forces in Action',
      'game.how_we_see': 'How We See',
      'game.earth_sun_moon': 'Earth, Sun & Moon',
      'game.circuits_conductors': 'Circuits & Conductors',
      'game.magnets_springs': 'Magnets & Springs',
      'game.sun_light_shadows': 'Sun, Light & Shadows',
      'game.changing_sounds': 'Changing Sounds',
      'game.friction': 'Friction',
      'game.light_dark': 'Light & Dark',
      'game.changing_state_water': 'Changing State of Water',
      'game.reversible_changes': 'Reversible Changes',
      'game.properties_materials': 'Properties of Materials',
      'game.rocks_minerals_soils': 'Rocks, Minerals & Soils',
      'game.melting_points': 'Melting Points',
      'game.solids_liquids_gases': 'Solids, Liquids and Gases',
      'game.heat_transfer': 'Heat Transfer',
      'game.addition_kids': 'Addition Game for Kids',
      'game.subtraction_kids': 'Subtraction Game for Kids',
      'game.multiplication_kids': 'Multiplication Game for Kids',
      'game.division_kids': 'Division Game for Kids',
      'game.shapes_kids': 'Shapes Game for Kids',
      'game.angles_kids': 'Angles Game for Kids',
      'game.measurements_kids': 'Measurements Game for Kids',
      'game.grids_coordinates_kids': 'Grids & Coordinates Game',
      'game.transformation_kids': 'Transformation Game for Kids',
      'game.fractions_kids': 'Fractions Game for Kids',
      'game.decimals_kids': 'Decimals Game for Kids',
      'game.number_patterns_kids': 'Number Patterns Game',
      'game.place_values_kids': 'Place Values Game for Kids',
      'game.calculator_kids': 'Calculator Game for Kids',
      'game.money_kids': 'Money Game for Kids',
      'game.problem_solving_kids': 'Problem Solving Game for Kids',
      'game.probability_kids': 'Probability Game for Kids',
      'game.percentages_kids': 'Percentages Game for Kids',
      'game.mean_median_mode_kids': 'Mean, Median & Mode Game',
      'game.frequency_tables_kids': 'Frequency Tables Game',
      'game.map_routes_directions_kids': 'Map Routes & Directions Game',
      'game.poetry_kids': 'Poetry Game for Kids',
      'game.non_fiction_kids': 'Non Fiction Game for Kids',
      'game.dictionary_kids': 'Dictionary Game for Kids',
      'game.punctuation_kids': 'Punctuation Games for Kids',
      'game.conjunction_kids': 'Conjunction Game for Kids',
      'game.prefix_suffix_kids': 'Prefix & Suffix Game',
      'game.verb_noun_adjective_kids': 'Verb, Noun, Adjective Game',
      'game.debate_kids': 'Debate Game for Kids',
      'game.newspaper_kids': 'Newspaper Game for Kids',
      'game.advertising': 'Advertising Game',
      'game.write_letter': 'Learn How to Write a Letter',
      'game.story_writing_kids': 'Story Writing Game for Kids',
      'game.instructions_kids': 'Instructions Game for Kids',
      'game.fun_crossword_kids': 'Fun Crossword Game for Kids',
      'game.letter_matching_kids': 'Letter Matching Game for Kids',
      'game.spiderman_spelling': 'Spiderman Spelling Game',
      'game.alphabet_kids': 'Alphabet Game for Kids',
      'game.easy_spelling_kids': 'Easy Spelling Game for Kids',
      'game.word_guessing_puzzle': 'Word Guessing Puzzle Game',
      'browser.ai_safe_search': 'AI Safe Search',
      'browser.ai_safe_search_desc':
          'Filters harmful topics directly in the SafePlay browser.',
      'browser.content_filters': 'Content Filters',
      'browser.block_social_desc':
          'Prevents Facebook, TikTok, Discord & similar sites.',
      'browser.block_social': 'Block Social Media',
      'browser.block_gambling': 'Block Gambling Sites',
      'browser.block_gambling_desc':
          'Stops betting, casino and loot-box content.',
      'browser.block_violence': 'Block Violent Media',
      'browser.block_violence_desc':
          'Removes graphic games, gore and unsafe forums.',
      'browser.allowed_sites': 'Allowed Sites',
      'browser.add_allowed_site': 'Add allowed site',
      'browser.allowed_placeholder': 'Enter site URL (e.g. example.com)',
      'browser.no_allowed_sites': 'No allowed sites added yet',
      'browser.blocked_keywords': 'Blocked Keywords',
      'browser.add_blocked_keyword': 'Add blocked keyword',
      'browser.keyword_placeholder':
          'Blacklist keywords like violent, graphic...',
      'browser.no_blocked_keywords': 'No blocked keywords added yet',
      'browser.whats_allowed': "What's allowed",
      'browser.whats_blocked': "What's blocked",
      'browser.allowed_empty_note':
          'Only SafePlay curated destinations will be accessible. Add trusted domains to whitelist them.',
      'browser.keyword_empty_note':
          'No custom keywords yet. Add phrases you never want to appear.',
      'browser.dialog_add_allowed_title': 'Add Allowed Site',
      'browser.dialog_add_allowed_hint': 'e.g., example.com',
      'browser.dialog_add_blocked_title': 'Add Blocked Keyword',
      'browser.dialog_add_blocked_hint': 'Enter keyword to block',
      'browser.safe_search_on': 'Safe Search On',
      'browser.safe_search_off': 'Safe Search Off',
      'browser.social_blocked': 'Social Apps Blocked',
      'browser.social_allowed': 'Social Apps Allowed',
      'browser.gambling_blocked': 'Gambling Blocked',
      'browser.gambling_allowed': 'Gambling Allowed',
      'browser.violence_blocked': 'Violence Blocked',
      'browser.violence_allowed': 'Violence Allowed',
      'browser.child_browser_title': "{name}'s Browser",
      'browser.cloud_rules': 'Cloud-backed safe browsing rules',
      'browser.syncing': 'Syncing latest settings...',
      'browser.using_defaults':
          'Using SafePlay defaults until the first cloud sync completes.',
      'browser.sync_never': 'Never synced yet',
      'browser.sync_just_now': 'Last synced just now',
      'browser.sync_minutes_single': 'Last synced 1 minute ago',
      'browser.sync_minutes_plural': 'Last synced {count} minutes ago',
      'browser.sync_hours_single': 'Last synced 1 hour ago',
      'browser.sync_hours_plural': 'Last synced {count} hours ago',
      'browser.sync_days_single': 'Last synced 1 day ago',
      'browser.sync_days_plural': 'Last synced {count} days ago',
      'onboard.parent.1.title': 'Welcome to SafePlay',
      'onboard.parent.1.subtitle': 'Your Child\'s Safety is Our Priority',
      'onboard.parent.1.desc':
          'SafePlay provides a secure, engaging learning environment where your children can explore, learn, and grow safely online.',
      'onboard.parent.1.h1': 'Age-appropriate content for all children',
      'onboard.parent.1.h2': 'AI-powered safety monitoring',
      'onboard.parent.1.h3': 'Educational games and activities',
      'onboard.parent.1.h4': 'Complete parental oversight',
      'onboard.parent.2.title': 'Manage Child Profiles',
      'onboard.parent.2.subtitle': 'Create & Customize Profiles',
      'onboard.parent.2.desc':
          'Add multiple children with personalized profiles. Set age groups, configure login methods, and track individual progress.',
      'onboard.parent.2.h1': 'Support for Junior and Bright age groups',
      'onboard.parent.2.h2': 'Customizable avatars and names',
      'onboard.parent.2.h3': 'Individual progress tracking',
      'onboard.parent.2.h4': 'Easy login setup for each child',
      'onboard.parent.3.title': 'Browser Controls',
      'onboard.parent.3.subtitle': 'Safe Internet Browsing',
      'onboard.parent.3.desc':
          'Configure comprehensive browser controls to ensure your children only access safe, age-appropriate content online.',
      'onboard.parent.3.h1': 'Safe search filtering enabled by default',
      'onboard.parent.3.h2': 'Block social media and harmful content',
      'onboard.parent.3.h3': 'Custom blocked keywords',
      'onboard.parent.3.h4': 'Whitelist trusted websites',
      'onboard.parent.4.title': 'Wellbeing Monitoring',
      'onboard.parent.4.subtitle': 'Track Emotional Health',
      'onboard.parent.4.desc':
          'Stay connected with your child\'s emotional wellbeing through regular check-ins and mood tracking reports.',
      'onboard.parent.4.h1': 'Weekly wellbeing check-ins',
      'onboard.parent.4.h2': 'Mood tracking and history',
      'onboard.parent.4.h3': 'Emotional health insights',
      'onboard.parent.4.h4': 'Early concern detection',
      'onboard.parent.5.title': 'Messaging Safety',
      'onboard.parent.5.subtitle': 'AI-Powered Protection',
      'onboard.parent.5.desc':
          'Our advanced AI monitors all messaging between students and teachers, instantly flagging any concerning content.',
      'onboard.parent.5.h1': 'Real-time message monitoring',
      'onboard.parent.5.h2': 'Profanity and bullying detection',
      'onboard.parent.5.h3': 'Instant parent notifications',
      'onboard.parent.5.h4': 'Complete conversation transparency',
      'onboard.parent.6.title': 'Activity Tracking',
      'onboard.parent.6.subtitle': 'Stay Informed',
      'onboard.parent.6.desc':
          'Monitor your child\'s learning journey with detailed activity reports, achievements, and progress metrics.',
      'onboard.parent.6.h1': 'Daily activity summaries',
      'onboard.parent.6.h2': 'Learning progress reports',
      'onboard.parent.6.h3': 'Achievement tracking',
      'onboard.parent.6.h4': 'Time spent analytics',
      'onboard.parent.7.title': 'Get Started',
      'onboard.parent.7.subtitle': 'You\'re All Set!',
      'onboard.parent.7.desc':
          'You\'re ready to create a safe learning environment for your children. Sign in to access your parent dashboard.',
      'onboard.parent.7.h1': 'Add your first child profile',
      'onboard.parent.7.h2': 'Configure safety settings',
      'onboard.parent.7.h3': 'Monitor progress anytime',
      'onboard.parent.7.h4': 'View activity reports',
    },
    'ar': {
      'lang.english': 'الإنجليزية',
      'lang.arabic': 'العربية',
      'action.continue': 'متابعة',
      'action.skip': 'تخطي',
      'action.get_started': 'ابدأ الآن',
      'action.next': 'التالي',
      'action.previous': 'السابق',
      'action.login': 'تسجيل الدخول',
      'action.signup': 'إنشاء حساب',
      'action.refresh': 'تحديث',
      'action.change_language': 'تغيير اللغة',
      'action.cancel': 'إلغاء',
      'action.delete': 'حذف',
      'action.ok': 'موافق',
      'action.retry': 'إعادة المحاولة',
      'greeting.morning': 'صباح الخير',
      'greeting.afternoon': 'مساء الخير',
      'greeting.evening': 'مساء الخير',
      'label.parent_portal': 'بوابة الوالدين',
      'label.safeplay_portal': 'بوابة سيف بلاي',
      'label.welcome_parent': 'مرحبًا بك في سيف بلاي',
      'label.parent_subtitle': 'سلامة طفلك هي أولويتنا',
      'label.language_prompt': 'اختر لغتك',
      'label.language_description':
          'يمكنك التبديل في أي وقت من القائمة داخل لوحة الوالدين.',
      'label.parent_login': 'تسجيل دخول الوالد',
      'label.parent_signup': 'إنشاء حساب ولي الأمر',
      'label.email': 'البريد الإلكتروني',
      'label.password': 'كلمة المرور',
      'label.forgot_password': 'هل نسيت كلمة المرور؟',
      'label.no_account': 'لا تملك حسابًا؟',
      'label.have_account': 'لديك حساب بالفعل؟',
      'label.home': 'لوحة الوالدين',
      'label.controls': 'ضوابط المتصفح',
      'label.wellbeing': 'تقارير الصحة النفسية',
      'label.messaging': 'سلامة المراسلة',
      'label.nav_home': 'الرئيسية',
      'label.nav_controls': 'الضوابط',
      'label.nav_wellbeing': 'الرفاه',
      'label.nav_alerts': 'التنبيهات',
      'label.ai_wellbeing': 'تقرير الذكاء الاصطناعي للصحة النفسية',
      'label.recent_checkins': 'أحدث تسجيلات الشعور',
      'label.this_weeks_mood': 'مزاج هذا الأسبوع',
      'label.browser_activity': 'سجل نشاط المتصفح',
      'label.privacy_note':
          'يتم عرض ملخصات عامة دون ملاحظات خام، للمساعدة على محادثات لطيفة.',
      'browser.summary_hint':
          'ملخص عام للنشاط الإلكتروني الأخير مع الحفاظ على الخصوصية.',
      'browser.error_title': 'تعذر تحميل ملخص نشاط التصفح الأخير.',
      'browser.empty': 'لا يوجد نشاط كافٍ لعرض ملخص حتى الآن.',
      'label.language_setting': 'اللغة',
      'label.language_setting_desc':
          'بدّل بين الإنجليزية والعربية لتجربة الوالد.',
      'settings.title': 'الإعدادات',
      'settings.subtitle': 'إدارة الحساب والتفضيلات',
      'settings.change_password': 'تغيير كلمة المرور',
      'settings.change_password_desc': 'حدّث كلمة مرور حسابك',
      'settings.notifications': 'الإشعارات',
      'settings.notifications_desc': 'إدارة تفضيلات الإشعارات',
      'settings.privacy': 'الخصوصية والأمان',
      'settings.privacy_desc': 'إدارة إعدادات الخصوصية',
      'settings.help': 'المساعدة والدعم',
      'settings.help_desc': 'احصل على مساعدة وتواصل مع الدعم',
      'settings.logout': 'تسجيل الخروج',
      'settings.delete_account': 'حذف الحساب',
      'settings.delete_account_desc': 'حذف حسابك وكل البيانات نهائيًا',
      'settings.sign_out': 'تسجيل الخروج',
      'dashboard.active_child': 'الطفل النشط',
      'dashboard.selected': 'المحدد',
      'dashboard.children': 'أطفال',
      'dashboard.streak': 'السلسلة',
      'dashboard.safety': 'الأمان',
      'dashboard.recent_activities': 'الأنشطة الأخيرة',
      'dashboard.screen_time': 'حد وقت الشاشة',
      'dashboard.screen_time_desc': 'الحد اليومي لـ ',
      'dashboard.enable_screen_time': 'تفعيل حد وقت الشاشة',
      'dashboard.daily_limit_label': 'الحد اليومي',
      'dashboard.auto_pause': 'إيقاف التطبيق تلقائيًا عند الوصول للحد اليومي',
      'dashboard.select_child_limits': 'اختر طفلًا لضبط الحدود',
      'dashboard.add_child': 'إضافة طفل',
      'dashboard.your_children': 'أطفالك',
      'dashboard.no_children': 'لا يوجد أطفال مضافون بعد',
      'dashboard.add_first_child': 'أضف أول طفل للبدء',
      'dashboard.remaining_time': 'متبقي من',
      'dashboard.select_child_prompt': 'اختر طفلًا',
      'dashboard.managing_children': 'إدارة {count} الأطفال',
      'dashboard.view_all': 'عرض الكل',
      'dashboard.view_less': 'عرض أقل',
      'dashboard.add_child_to_see_activities': 'أضف طفلًا لعرض أنشطته الأخيرة.',
      'dashboard.no_recent_activities': 'لا توجد أنشطة بعد لـ {name}.',
      'dashboard.cached_insights':
          'يتم عرض بيانات محفوظة مؤقتًا. حدّث للمحاولة مرة أخرى.',
      'dashboard.quick_presets': 'إعدادات سريعة',
      'dashboard.minutes': 'دقائق',
      'dashboard.hours': 'ساعات',
      'dashboard.limit_reached':
          'عند الوصول للحد الزمني، سيتوقف التطبيق تلقائيًا.',
      'dashboard.remaining_time_text': '{time} متبقية من {total}',
      'dashboard.age_label': 'العمر',
      'dashboard.ready': 'جاهز',
      'dashboard.unlock_today': 'إلغاء القفل لليوم',
      'browser.controls_title': 'ضوابط المتصفح',
      'browser.safe_search': 'البحث الآمن',
      'browser.note_privacy':
          'هذا الملخص يحترم الخصوصية بعرض أنماط نشاط مجردة دون تفاصيل شخصية.',
      'wellbeing.overview': 'الرفاه العام',
      'wellbeing.recent_checkins': 'أحدث تسجيلات الشعور',
      'wellbeing.note_privacy':
          'الملخصات ذات المستوى العام تحافظ على خصوصية الأطفال مع إظهار اتجاهات يمكن للوالدين التصرف حيالها.',
      'wellbeing.add_child_title': 'أضف طفلاً أولاً',
      'wellbeing.add_child_subtitle': 'تحتاج إلى إضافة طفل قبل عرض تقارير الصحة النفسية.',
      'wellbeing.select_child_title': 'اختر طفلاً',
      'wellbeing.select_child_subtitle': 'اختر طفلاً من القائمة أعلاه لعرض بيانات رفاهه.',
      'wellbeing.no_checkins_title': 'لا توجد تسجيلات حتى الآن',
      'wellbeing.no_checkins_message': 'شجّع {name} على مشاركة شعوره من لوحته.',
      'wellbeing.child_header': 'صحة {name} النفسية',
      'wellbeing.last_shared': 'آخر مشاركة كانت في {timestamp}',
      'wellbeing.latest_note': 'أحدث ملاحظة: {note}',
      'wellbeing.score_label': 'النتيجة',
      'wellbeing.no_mood_week': 'لا توجد تسجيلات مزاج لهذا الأسبوع.',
      'wellbeing.no_recent_checkins': 'لا توجد تسجيلات رفاهية بعد.',
      'wellbeing.no_note_added': 'لم تتم إضافة ملاحظة',
      'wellbeing.checkin_yesterday': 'أمس • {time}',
      'wellbeing.checkin_day_time': '{day} • {time}',
      'wellbeing.mood.amazing': 'رائع',
      'wellbeing.mood.happy': 'سعيد',
      'wellbeing.mood.good': 'جيد',
      'wellbeing.mood.okay': 'مقبول',
      'wellbeing.mood.sad': 'حزين',
      'wellbeing.mood.upset': 'منزعج',
      'wellbeing.tag.mood_trends': 'اتجاهات المزاج',
      'wellbeing.tag.recent_week': 'هذا الأسبوع',
      'messaging.title': 'سلامة المراسلة',
      'messaging.alerts': 'تنبيهات الذكاء الاصطناعي',
      'messaging.alert_inappropriate': 'لغة غير لائقة',
      'messaging.alert_detected': 'تم الاكتشاف مؤخرًا',
      'activity.teacher_assigned': 'جلسة مخصصة من المعلم',
      'activity.single_min_session': 'جلسة دقيقة واحدة',
      'activity.minutes_session': 'جلسة لمدة {minutes} دقيقة',
      'activity.learning': 'تعلّم',
      'child.age_value': 'العمر {age}',
      'child.age_not_set': 'العمر غير محدد',
      'child.grade_value': 'الصف {grade}',
      'child.streak_value': 'سلسلة إنجاز {days} يوم',
      'child.login_ready': 'جاهز لتسجيل الدخول',
      'child.setup_login': 'إعداد تسجيل الدخول',
      'child.age_group_junior': 'جونيور',
      'child.age_group_bright': 'برايت',
      'child.list_header': 'أطفالك ({count})',
      'child.empty_title': 'لا يوجد أطفال مضافون بعد',
      'child.empty_subtitle': 'أضف طفلك الأول لبدء متابعة رحلته التعليمية',
      'child.empty_button': 'أضف طفلك الأول',
      'child.add.title': 'إضافة طفل',
      'child.add.header': 'إنشاء ملف طفل',
      'child.add.subtitle': 'أضف طفلك لبدء متابعة رحلته التعليمية',
      'child.add.submit': 'إنشاء ملف الطفل',
      'child.add.success': 'تم إنشاء ملف الطفل بنجاح!',
      'child.form.name_label': 'اسم الطفل',
      'child.form.name_error': 'يرجى إدخال اسم طفلك',
      'child.form.age_label': 'العمر',
      'child.form.age_helper': 'أدخل عمرًا بين 6 و12 عامًا',
      'child.form.age_error': 'يرجى إدخال عمر طفلك',
      'child.form.age_range_error': 'يجب أن يكون العمر رقمًا بين 6 و12',
      'child.form.gender_label': 'الجنس',
      'child.form.gender_male': 'ذكر',
      'child.form.gender_female': 'أنثى',
      'child.form.gender_missing': 'يرجى اختيار جنس طفلك',
      'child.form.age_group_label': 'الفئة العمرية',
      'child.form.age_group_junior': 'مستكشف جونيور',
      'child.form.age_group_bright': 'عقول برايت',
      'child.form.age_group_junior_desc': 'الأعمار 6-8',
      'child.form.age_group_bright_desc': 'الأعمار 9-12',
      'child.form.age_mismatch_title': 'عدم تطابق العمر',
      'child.form.age_mismatch_body':
          'عمر طفلك {age} عامًا، لكن {group} مصمم للأعمار {range}.',
      'child.form.age_mismatch_hint':
          'يرجى اختيار الفئة العمرية المناسبة أو تعديل العمر.',
      'child.edit.title': 'تعديل ملف الطفل',
      'child.edit.header': 'تعديل ملف {name}',
      'child.edit.subtitle': 'حدّث معلومات طفلك وإعدادات الدخول',
      'child.edit.submit': 'تحديث ملف الطفل',
      'child.edit.success': 'تم تحديث ملف الطفل بنجاح!',
      'child.auth.section_title': 'المصادقة',
      'child.auth.junior': 'مصادقة جونيور (٤ رموز تعبيرية)',
      'child.auth.bright': 'مصادقة برايت (٣ صور + رقم سري)',
      'child.auth.none': 'لم يتم إعداد المصادقة',
      'child.auth.change': 'تغيير المصادقة',
      'child.auth.setup': 'إعداد المصادقة',
      'child.delete.title': 'حذف ملف الطفل',
      'child.delete.confirm':
          'هل أنت متأكد من حذف ملف {name}؟ هذا الإجراء لا يمكن التراجع عنه.',
      'auth.setup.title': 'إعداد تسجيل دخول {name}',
      'auth.setup.instructions_emoji':
          'ساعد طفلك على إنشاء كلمة مرور بالصور يسهل تذكرها.',
      'auth.setup.instructions_bright':
          'ساعد طفلك على إعداد دخول آمن بالصور ورقم سري.',
      'auth.setup.how_it_works': 'كيف يعمل:',
      'auth.setup.emoji.step1': 'اختر ٤ صور إيموجي يحبها طفلك',
      'auth.setup.emoji.step2': 'تذكّر الترتيب الذي اخترته',
      'auth.setup.emoji.step3': 'سيستخدم طفلك هذا التسلسل لتسجيل الدخول',
      'auth.setup.emoji.step4': 'تأكد أنه سهل التذكر!',
      'auth.setup.pictures.step1': 'اختر ٣ صور يحبها طفلك',
      'auth.setup.pictures.step2': 'أنشئ رقمًا سريًا من ٤ أرقام',
      'auth.setup.pictures.step3': 'سيستخدم طفلك الصورتين والرقم للدخول',
      'auth.setup.pictures.step4': 'تأكد أن بإمكانه تذكرهما!',
      'auth.setup.choose_emojis_title': 'اختر ٤ إيموجي',
      'auth.setup.choose_emojis_subtitle':
          'اختر ٤ صور إيموجي سيستخدمها {name} لتسجيل الدخول.',
      'auth.setup.choose_pictures_title': 'اختر ٣ صور',
      'auth.setup.choose_pictures_subtitle':
          'اختر ٣ صور سيستخدمها {name} لتسجيل الدخول.',
      'auth.setup.selected_count': 'المختار ({current}/{total}):',
      'auth.setup.confirm_title': 'تأكيد تسجيل دخول {name}',
      'auth.setup.confirm_sequence_subtitle':
          'هذا هو التسلسل الذي سيستخدمه {name} لتسجيل الدخول:',
      'auth.setup.confirm_login_subtitle':
          'هذا ما سيستخدمه {name} لتسجيل الدخول:',
      'auth.setup.login_sequence': 'تسلسل تسجيل الدخول',
      'auth.setup.remember_sequence': 'تأكد أن {name} يستطيع تذكر هذا التسلسل!',
      'auth.setup.remember_pin': 'تأكد أن {name} يستطيع تذكر هذا الرقم السري!',
      'auth.setup.back': 'رجوع',
      'auth.setup.start_selection': 'ابدأ الاختيار',
      'auth.setup.confirm_selection': 'تأكيد الاختيار',
      'auth.setup.save_login': 'حفظ تسجيل الدخول',
      'auth.setup.next': 'التالي',
      'auth.setup.select_pictures': 'اختر الصور',
      'auth.setup.create_pin': 'أنشئ الرقم السري',
      'auth.setup.review_setup': 'مراجعة الإعداد',
      'auth.setup.saving': 'جاري الحفظ...',
      'auth.setup.pin_title': 'إنشاء رقم سري',
      'auth.setup.pin_subtitle':
          'أنشئ رقمًا سريًا من ٤ أرقام يمكن لـ {name} تذكره.',
      'auth.setup.pin_label': 'رقم سري من ٤ أرقام',
      'auth.setup.pin_helper': 'أدخل رقمًا من ٤ أرقام (مثال: 1234)',
      'auth.setup.pin_error_length': 'يجب أن يكون الرقم السري ٤ أرقام بالضبط',
      'auth.setup.pin_error_numeric': 'يجب أن يحتوي الرقم السري على أرقام فقط',
      'auth.setup.pin_confirm_label': 'تأكيد الرقم السري',
      'auth.setup.pin_error_mismatch': 'الأرقام السرية غير متطابقة',
      'auth.setup.pin_validation_prompt': 'أدخل رقمًا سريًا من ٤ أرقام ثم أكده',
      'auth.setup.pin_validation_short': 'يجب أن يكون الرقم السري ٤ أرقام',
      'auth.setup.pin_validation_numeric':
          'يجب أن يحتوي الرقم السري على أرقام فقط',
      'auth.setup.pin_validation_confirm_prompt': 'يرجى تأكيد الرقم السري',
      'auth.setup.pin_validation_confirm_short':
          'يجب أن يكون تأكيد الرقم السري ٤ أرقام',
      'auth.setup.pin_validation_mismatch': 'الأرقام السرية غير متطابقة',
      'auth.setup.pin_validation_valid': 'الرقم السري صالح!',
      'auth.setup.confirm_selected_pictures': 'الصور المختارة:',
      'auth.setup.confirm_pin_label': 'الرقم السري:',
      'auth.setup.success': 'تم إكمال إعداد تسجيل الدخول بنجاح!',
      'auth.setup.error_prefix': 'خطأ: ',
      'game.letter_sound_adventure': 'مغامرة أصوات الحروف',
      'game.math_maze': 'متاهة الرياضيات',
      'game.science_quiz': 'اختبار العلوم',
      'game.reading_quest': 'رحلة القراءة',
      'game.shapes_sorter': 'فرز الأشكال',
      'game.number_grid_race': 'سباق شبكة الأرقام',
      'game.koala_counter_adventure': 'مغامرة كوالا العدّ',
      'game.ordinal_order_challenge': 'تحدي الترتيب التتابعي',
      'game.pattern_builder': 'منشئ الأنماط',
      'game.bubblepop_grammar': 'فقاعات القواعد',
      'game.seashell_quiz': 'اختبار الأصداف',
      'game.fish_tank_quiz': 'اختبار حوض الأسماك',
      'game.add_equations': 'معادلات الجمع',
      'game.fraction_navigator': 'ملاحة الكسور',
      'game.inverse_operation_chain': 'سلسلة العمليات العكسية',
      'game.data_visualization_lab': 'مختبر تصور البيانات',
      'game.cartesian_grid_explorer': 'مستكشف الإحداثيات',
      'game.memory_match': 'مطابقة الذاكرة',
      'game.word_builder': 'منشئ الكلمات',
      'game.story_sequencer': 'مرتب القصص',
      'game.math_adventures': 'مغامرات الرياضيات',
      'game.reading_adventures': 'مغامرات القراءة',
      'game.science_adventures': 'مغامرات العلوم',
      'game.number_hunt': 'مطاردة الأرقام',
      'game.koala_jumps': 'قفزات الكوالا',
      'game.pattern_wizard': 'ساحر الأنماط',
      'game.equality_explorer_basics': 'مستكشف التساوي: الأساسيات',
      'game.area_model_introduction': 'مقدمة نموذج المساحة',
      'game.mean_share_balance': 'المتوسط: التوزيع والتوازن',
      'game.balancing_act': 'لعبة التوازن',
      'game.states_of_matter_simulation': 'محاكاة حالات المادة',
      'game.balloons_static_electricity': 'البالونات والكهرباء الساكنة',
      'game.exploring_density': 'استكشاف الكثافة',
      'game.food_chains': 'السلاسل الغذائية',
      'game.microorganisms': 'الكائنات الحية الدقيقة',
      'game.human_body_health_growth': 'صحة ونمو جسم الإنسان',
      'game.teeth_eating': 'الأسنان والتغذية',
      'game.plants_animals': 'النباتات والحيوانات',
      'game.keeping_healthy': 'الحفاظ على الصحة',
      'game.how_plants_grow': 'كيف تنمو النباتات',
      'game.skeleton_bones': 'الهيكل العظمي والعظام',
      'game.plant_animal_differences': 'اختلافات النبات والحيوان',
      'game.life_cycle_plant': 'دورة حياة النبات',
      'game.electricity_circuits': 'دوائر الكهرباء',
      'game.forces_in_action': 'القوى في الحركة',
      'game.how_we_see': 'كيف نرى',
      'game.earth_sun_moon': 'الأرض والشمس والقمر',
      'game.circuits_conductors': 'الدوائر والموصلات',
      'game.magnets_springs': 'المغانط والزنبركات',
      'game.sun_light_shadows': 'الشمس والضوء والظلال',
      'game.changing_sounds': 'تغير الأصوات',
      'game.friction': 'الاحتكاك',
      'game.light_dark': 'النور والظلام',
      'game.changing_state_water': 'تغير حالة الماء',
      'game.reversible_changes': 'تغيرات قابلة للعكس',
      'game.properties_materials': 'خصائص المواد',
      'game.rocks_minerals_soils': 'الصخور والمعادن والتربة',
      'game.melting_points': 'نقاط الانصهار',
      'game.solids_liquids_gases': 'الصلبة والسائلة والغازية',
      'game.heat_transfer': 'انتقال الحرارة',
      'game.addition_kids': 'لعبة الجمع للأطفال',
      'game.subtraction_kids': 'لعبة الطرح للأطفال',
      'game.multiplication_kids': 'لعبة الضرب للأطفال',
      'game.division_kids': 'لعبة القسمة للأطفال',
      'game.shapes_kids': 'لعبة الأشكال للأطفال',
      'game.angles_kids': 'لعبة الزوايا للأطفال',
      'game.measurements_kids': 'لعبة القياسات للأطفال',
      'game.grids_coordinates_kids': 'لعبة الشبكات والإحداثيات',
      'game.transformation_kids': 'لعبة التحويلات للأطفال',
      'game.fractions_kids': 'لعبة الكسور للأطفال',
      'game.decimals_kids': 'لعبة الأعداد العشرية للأطفال',
      'game.number_patterns_kids': 'لعبة الأنماط العددية للأطفال',
      'game.place_values_kids': 'لعبة القيم المكانية للأطفال',
      'game.calculator_kids': 'لعبة الآلة الحاسبة للأطفال',
      'game.money_kids': 'لعبة النقود للأطفال',
      'game.problem_solving_kids': 'لعبة حل المشكلات للأطفال',
      'game.probability_kids': 'لعبة الاحتمالات للأطفال',
      'game.percentages_kids': 'لعبة النسب المئوية للأطفال',
      'game.mean_median_mode_kids': 'لعبة المتوسط والوسيط والمنوال',
      'game.frequency_tables_kids': 'لعبة جداول التكرار',
      'game.map_routes_directions_kids': 'لعبة الخرائط والاتجاهات',
      'game.poetry_kids': 'لعبة الشعر للأطفال',
      'game.non_fiction_kids': 'لعبة غير القصص للأطفال',
      'game.dictionary_kids': 'لعبة القاموس للأطفال',
      'game.punctuation_kids': 'لعبة علامات الترقيم للأطفال',
      'game.conjunction_kids': 'لعبة الروابط للأطفال',
      'game.prefix_suffix_kids': 'لعبة البادئات واللواحق',
      'game.verb_noun_adjective_kids': 'لعبة فعل/اسم/صفة للأطفال',
      'game.debate_kids': 'لعبة المناظرة للأطفال',
      'game.newspaper_kids': 'لعبة الصحيفة للأطفال',
      'game.advertising': 'لعبة الإعلان',
      'game.write_letter': 'تعلم كتابة رسالة',
      'game.story_writing_kids': 'لعبة كتابة القصص للأطفال',
      'game.instructions_kids': 'لعبة التعليمات للأطفال',
      'game.fun_crossword_kids': 'لعبة الكلمات المتقاطعة الممتعة',
      'game.letter_matching_kids': 'لعبة مطابقة الحروف للأطفال',
      'game.spiderman_spelling': 'لعبة تهجئة سبايدرمان',
      'game.alphabet_kids': 'لعبة الحروف للأطفال',
      'game.easy_spelling_kids': 'لعبة التهجئة السهلة للأطفال',
      'game.word_guessing_puzzle': 'لعبة تخمين الكلمات',
      'browser.ai_safe_search': 'بحث آمن بالذكاء الاصطناعي',
      'browser.ai_safe_search_desc':
          'يحظر المواضيع الضارة داخل متصفح سيف بلاي.',
      'browser.content_filters': 'مرشحات المحتوى',
      'browser.block_social': 'حظر التواصل الاجتماعي',
      'browser.block_social_desc':
          'يمنع مواقع مثل فيسبوك، تيك توك، ديسكورد وغيرها.',
      'browser.block_gambling': 'حظر مواقع المقامرة',
      'browser.block_gambling_desc':
          'يوقف المحتوى المرتبط بالمراهنات والكازينوهات والصناديق الوهمية.',
      'browser.block_violence': 'حظر المحتوى العنيف',
      'browser.block_violence_desc':
          'يزيل الألعاب الدموية والمنتديات غير الآمنة.',
      'browser.allowed_sites': 'المواقع المسموح بها',
      'browser.add_allowed_site': 'إضافة موقع مسموح',
      'browser.allowed_placeholder': 'أدخل رابط الموقع (مثال: example.com)',
      'browser.no_allowed_sites': 'لا توجد مواقع مسموح بها بعد',
      'browser.blocked_keywords': 'الكلمات المحظورة',
      'browser.add_blocked_keyword': 'إضافة كلمة محظورة',
      'browser.keyword_placeholder': 'أضف كلمات مثل: عنيف، دموي...',
      'browser.no_blocked_keywords': 'لا توجد كلمات محظورة بعد',
      'browser.whats_allowed': 'ما هو مسموح',
      'browser.whats_blocked': 'ما هو محظور',
      'onboard.parent.1.title': 'مرحبًا بك في سيف بلاي',
      'onboard.parent.1.subtitle': 'سلامة طفلك هي أولويتنا',
      'onboard.parent.1.desc':
          'يقدم سيف بلاي بيئة تعلم آمنة وجذابة ليكتشف الأطفال ويتعلموا وينموا بثقة.',
      'onboard.parent.1.h1': 'محتوى مناسب للعمر لكل طفل',
      'onboard.parent.1.h2': 'مراقبة أمان مدعومة بالذكاء الاصطناعي',
      'onboard.parent.1.h3': 'ألعاب وأنشطة تعليمية',
      'onboard.parent.1.h4': 'رقابة كاملة للوالدين',
      'onboard.parent.2.title': 'إدارة ملفات الأطفال',
      'onboard.parent.2.subtitle': 'إنشاء وتخصيص الملفات',
      'onboard.parent.2.desc':
          'أضف عدة أطفال بملفات شخصية. حدد الفئة العمرية، واضبط طرق الدخول، وتتبع التقدم لكل طفل.',
      'onboard.parent.2.h1': 'دعم لمجموعتي الأعمار جونيور وبرايت',
      'onboard.parent.2.h2': 'صور وأسماء قابلة للتخصيص',
      'onboard.parent.2.h3': 'تتبع تقدم فردي',
      'onboard.parent.2.h4': 'إعداد تسجيل دخول سهل لكل طفل',
      'onboard.parent.3.title': 'ضوابط المتصفح',
      'onboard.parent.3.subtitle': 'تصفح آمن للإنترنت',
      'onboard.parent.3.desc':
          'اضبط ضوابط المتصفح لضمان وصول أطفالك إلى محتوى آمن ومناسب لأعمارهم فقط.',
      'onboard.parent.3.h1': 'تفعيل البحث الآمن افتراضيًا',
      'onboard.parent.3.h2': 'حظر التواصل الاجتماعي والمحتوى الضار',
      'onboard.parent.3.h3': 'كلمات محظورة مخصصة',
      'onboard.parent.3.h4': 'قائمة بيضاء للمواقع الموثوقة',
      'onboard.parent.4.title': 'مراقبة الرفاه',
      'onboard.parent.4.subtitle': 'تتبع الحالة الشعورية',
      'onboard.parent.4.desc':
          'ابقَ على اتصال بصحة طفلك النفسية عبر تسجيلات الشعور المنتظمة وتقارير المزاج.',
      'onboard.parent.4.h1': 'تسجيل شعور أسبوعي',
      'onboard.parent.4.h2': 'تتبع المزاج والسجل',
      'onboard.parent.4.h3': 'رؤى للصحة النفسية',
      'onboard.parent.4.h4': 'اكتشاف مبكر للمخاوف',
      'onboard.parent.5.title': 'سلامة المراسلة',
      'onboard.parent.5.subtitle': 'حماية بالذكاء الاصطناعي',
      'onboard.parent.5.desc':
          'يُراقب الذكاء الاصطناعي الرسائل بين الطلاب والمعلمين ويبلغ فورًا عن أي محتوى مقلق.',
      'onboard.parent.5.h1': 'مراقبة الرسائل لحظيًا',
      'onboard.parent.5.h2': 'كشف الألفاظ الجارحة والتنمر',
      'onboard.parent.5.h3': 'تنبيهات فورية للوالدين',
      'onboard.parent.5.h4': 'شفافية كاملة للمحادثات',
      'onboard.parent.6.title': 'تتبع النشاط',
      'onboard.parent.6.subtitle': 'ابقَ على اطلاع',
      'onboard.parent.6.desc':
          'راقب رحلة تعلم طفلك بتقارير نشاط مفصلة، وإنجازات، ومقاييس تقدم.',
      'onboard.parent.6.h1': 'ملخصات نشاط يومية',
      'onboard.parent.6.h2': 'تقارير تقدم التعلم',
      'onboard.parent.6.h3': 'تتبع الإنجازات',
      'onboard.parent.6.h4': 'تحليلات وقت الاستخدام',
      'onboard.parent.7.title': 'ابدأ الآن',
      'onboard.parent.7.subtitle': 'كل شيء جاهز!',
      'onboard.parent.7.desc':
          'أنت جاهز لإنشاء بيئة تعلم آمنة لأطفالك. سجّل الدخول للوصول إلى لوحة الوالد.',
      'onboard.parent.7.h1': 'أضف أول ملف لطفلك',
      'onboard.parent.7.h2': 'اضبط إعدادات الأمان',
      'onboard.parent.7.h3': 'راقب التقدم في أي وقت',
      'onboard.parent.7.h4': 'اعرض تقارير النشاط',
      'browser.allowed_empty_note':
          'سيتم السماح فقط بوجهات سيف بلاي المنسقة. أضف مواقع موثوقة لإدراجها في القائمة البيضاء.',
      'browser.keyword_empty_note':
          'لا توجد كلمات مخصصة بعد. أضف عبارات لا تريد ظهورها إطلاقاً.',
      'browser.dialog_add_allowed_title': 'إضافة موقع مسموح',
      'browser.dialog_add_allowed_hint': 'مثال: example.com',
      'browser.dialog_add_blocked_title': 'إضافة كلمة محظورة',
      'browser.dialog_add_blocked_hint': 'أدخل الكلمة المراد حظرها',
      'browser.safe_search_on': 'البحث الآمن مفعل',
      'browser.safe_search_off': 'البحث الآمن معطل',
      'browser.social_blocked': 'تطبيقات التواصل محظورة',
      'browser.social_allowed': 'تطبيقات التواصل مسموحة',
      'browser.gambling_blocked': 'المقامرة محظورة',
      'browser.gambling_allowed': 'المقامرة مسموحة',
      'browser.violence_blocked': 'المحتوى العنيف محظور',
      'browser.violence_allowed': 'المحتوى العنيف مسموح',
      'browser.child_browser_title': 'متصفح {name}',
      'browser.cloud_rules': 'قواعد تصفح آمن مدعومة بالسحابة',
      'browser.syncing': 'جاري مزامنة الإعدادات الأخيرة...',
      'browser.using_defaults':
          'يتم استخدام إعدادات سيف بلاي الافتراضية حتى يكتمل التزامن السحابي الأول.',
      'browser.sync_never': 'لم تتم المزامنة بعد',
      'browser.sync_just_now': 'آخر مزامنة للتو',
      'browser.sync_minutes_single': 'آخر مزامنة منذ دقيقة واحدة',
      'browser.sync_minutes_plural': 'آخر مزامنة منذ {count} دقيقة',
      'browser.sync_hours_single': 'آخر مزامنة منذ ساعة واحدة',
      'browser.sync_hours_plural': 'آخر مزامنة منذ {count} ساعة',
      'browser.sync_days_single': 'آخر مزامنة منذ يوم واحد',
      'browser.sync_days_plural': 'آخر مزامنة منذ {count} يوم',
    },
  };
  String t(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();
  @override
  bool isSupported(Locale locale) =>
      ['en', 'ar'].contains(locale.languageCode.toLowerCase());
  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension AppLocalizationsExtension on BuildContext {
  AppLocalizations get loc => AppLocalizations.of(this);
}

extension LocalizedString on String {
  String tr(BuildContext context) => AppLocalizations.of(context).t(this);
}
