// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhBqTIm96pxabRa90TJOGSUYew7SSVe8s',
    appId: '1:482780859595:web:34be1ebb20c162dfb0df4e',
    messagingSenderId: '482780859595',
    projectId: 'safeplay-portal',
    authDomain: 'safeplay-portal.firebaseapp.com',
    storageBucket: 'safeplay-portal.firebasestorage.app',
    measurementId: 'G-G3WG81E45Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHtkAiMS9DbA8K0pUqZ49Q8zkdUtm6u4I',
    appId: '1:482780859595:android:1d36f4aa1bfdc11cb0df4e',
    messagingSenderId: '482780859595',
    projectId: 'safeplay-portal',
    storageBucket: 'safeplay-portal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTdJgb5Br45vqFzzfJP_MDB9wk3tmsj3w',
    appId: '1:482780859595:ios:524fe23c5dbfb526b0df4e',
    messagingSenderId: '482780859595',
    projectId: 'safeplay-portal',
    storageBucket: 'safeplay-portal.firebasestorage.app',
    iosBundleId: 'com.example.safeplayMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTdJgb5Br45vqFzzfJP_MDB9wk3tmsj3w',
    appId: '1:482780859595:ios:524fe23c5dbfb526b0df4e',
    messagingSenderId: '482780859595',
    projectId: 'safeplay-portal',
    storageBucket: 'safeplay-portal.firebasestorage.app',
    iosBundleId: 'com.example.safeplayMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhBqTIm96pxabRa90TJOGSUYew7SSVe8s',
    appId: '1:482780859595:web:12130ff6de159fbeb0df4e',
    messagingSenderId: '482780859595',
    projectId: 'safeplay-portal',
    authDomain: 'safeplay-portal.firebaseapp.com',
    storageBucket: 'safeplay-portal.firebasestorage.app',
    measurementId: 'G-S9CCZ632VB',
  );

}